export const indonesianProvinces = [
  "Aceh",
  "Bali",
  "Bangka Belitung",
  "Banten",
  "Bengkulu",
  "DI Yogyakarta",
  "DKI Jakarta",
  "Gorontalo",
  "Jambi",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Kalimantan Barat",
  "Kalimantan Selatan",
  "Kalimantan Tengah",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Kepulauan Riau",
  "Lampung",
  "Maluku",
  "Maluku Utara",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Papua",
  "Papua Barat",
  "Papua Selatan",
  "Papua Tengah",
  "Papua Pegunungan",
  "Riau",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tengah",
  "Sulawesi Tenggara",
  "Sulawesi Utara",
  "Sumatera Barat",
  "Sumatera Selatan",
  "Sumatera Utara",
]

export const getCitiesByProvince = (province: string) => {
  const cities: Record<string, string[]> = {
    "Aceh": ["Banda Aceh", "Langsa", "Lhokseumawe", "Sabang", "Subulussalam", "Aceh Besar", "Aceh Barat", "Aceh Barat Daya", "Aceh Jaya", "Aceh Selatan", "Aceh Singkil", "Aceh Tamiang", "Aceh Tengah", "Aceh Tenggara", "Aceh Timur", "Aceh Utara", "Bener Meriah", "Gayo Lues", "Nagan Raya", "Pidie", "Pidie Jaya", "Simeulue"],
    "Bali": ["Denpasar", "Badung", "Gianyar", "Tabanan", "Bangli", "Klungkung", "Buleleng", "Jembrana", "Karangasem"],
    "Bangka Belitung": ["Pangkal Pinang", "Tanjung Pandan", "Bangka", "Bangka Barat", "Bangka Selatan", "Bangka Tengah", "Belitung", "Belitung Timur"],
    "Banten": ["Serang", "Tangerang", "Tangerang Selatan", "Cilegon", "Pandeglang", "Lebak", "Tangerang"],
    "Bengkulu": ["Bengkulu", "Kaur", "Kepahiang", "Lebong", "Muko-Muko", "Rejang Lebong", "Seluma"],
    "DI Yogyakarta": ["Yogyakarta", "Sleman", "Bantul", "Gunung Kidul", "Kulon Progo"],
    "DKI Jakarta": ["Jakarta Pusat", "Jakarta Utara", "Jakarta Selatan", "Jakarta Timur", "Jakarta Barat", "Kepulauan Seribu"],
    "Gorontalo": ["Gorontalo", "Bone Bolango", "Boalemo", "Gorontalo Selatan", "Gorontalo Utara", "Pohuwato"],
    "Jambi": ["Jambi", "Sungai Penuh", "Batang Hari", "Bungo", "Kerinci", "Merangin", "Muaro Jambi", "Sarolangun", "Tanjung Jabung Barat", "Tanjung Jabung Timur", "Tebo"],
    "Jawa Barat": ["Bandung", "Bekasi", "Bogor", "Cimahi", "Cirebon", "Depok", "Sukabumi", "Tasikmalaya", "Banjar", "Bandung Barat", "Bekasi", "Bogor", "Ciamis", "Cianjur", "Garut", "Indramayu", "Karawang", "Kuningan", "Majalengka", "Pangandaran", "Purwakarta", "Subang", "Sukabumi", "Sumedang"],
    "Jawa Tengah": ["Semarang", "Surakarta", "Salatiga", "Magelang", "Pekalongan", "Tegal", "Banjarnegara", "Batang", "Blora", "Boyolali", "Brebes", "Cilacap", "Demak", "Grobogan", "Jepara", "Karanganyar", "Kebumen", "Kendal", "Klaten", "Kudus", "Magelang", "Pati", "Pekalongan", "Pemalang", "Purworejo", "Rembang", "Semarang", "Sragen", "Sukoharjo", "Tegal", "Temanggung", "Wonogiri", "Wonosobo"],
    "Jawa Timur": ["Surabaya", "Malang", "Kediri", "Madiun", "Pasuruan", "Probolinggo", "Blitar", "Mojokerto", "Batu", "Banyuwangi", "Bondowoso", "Gresik", "Jember", "Jombang", "Kediri", "Lamongan", "Lumajang", "Madiun", "Magetan", "Malang", "Mojokerto", "Nganjuk", "Ngawi", "Pacitan", "Pamekasan", "Pasuruan", "Ponorogo", "Probolinggo", "Sampang", "Sidoarjo", "Situbondo", "Sumenep", "Tuban", "Tulungagung"],
    "Kalimantan Barat": ["Pontianak", "Singkawang", "Bengkayang", "Kapuas Hulu", "Kayong Utara", "Ketapang", "Kubu Raya", "Landak", "Melawi", "Sambas", "Sekadau", "Sanggau", "Sintang"],
    "Kalimantan Selatan": ["Banjarmasin", "Banjarbaru", "Balangan", "Barito Kuala", "Barito Selatan", "Barito Timur", "Hulu Sungai Selatan", "Hulu Sungai Tengah", "Hulu Sungai Utara", "Kotabaru", "Tabalong", "Tanah Bumbu", "Tanah Laut"],
    "Kalimantan Tengah": ["Palangka Raya", "Barito Selatan", "Barito Timur", "Gunung Mas", "Kapuas", "Katingan", "Kotawaringin Barat", "Kotawaringin Timur", "Lamandau", "Murung Raya", "Pulang Pisau", "Sukamara", "Seruyan", "Tumbang Hulu"],
    "Kalimantan Timur": ["Samarinda", "Balikpapan", "Bontang", "Berau", "Kutai Barat", "Kutai Kartanegara", "Kutai Timur", "Mahakam Hulu", "Paser", "Penajam Paser Utara"],
    "Kalimantan Utara": ["Tanjung Selor", "Bulungan", "Malinau", "Nunukan", "Tana Tidung"],
    "Kepulauan Riau": ["Batam", "Tanjung Pinang", "Anambas", "Bintan", "Karimun", "Kepulauan Anambas", "Kepulauan Riau", "Lingga", "Natuna"],
    "Lampung": ["Bandar Lampung", "Metro", "Lampung Barat", "Lampung Selatan", "Lampung Tengah", "Lampung Timur", "Lampung Utara", "Mesuji", "Pesawaran", "Pesisir Barat", "Tanggamus", "Tulang Bawang", "Tulang Bawang Barat", "Way Kanan"],
    "Maluku": ["Ambon", "Tual", "Buru", "Kepulauan Aru", "Kepulauan Kai", "Maluku Barat Daya", "Maluku Tengah", "Maluku Tenggara", "Maluku Tenggara Barat", "Seram Bagian Barat", "Seram Bagian Timur"],
    "Maluku Utara": ["Ternate", "Tidore", "Halmahera Barat", "Halmahera Selatan", "Halmahera Tengah", "Halmahera Timur", "Halmahera Utara", "Kepulauan Sangihe", "Kepulauan Siau Tagulandang", "Kepulauan Talaud", "Pulau Morotai", "Pulau Taliabu"],
    "Nusa Tenggara Barat": ["Mataram", "Bima", "Bima", "Dompu", "Lombok Barat", "Lombok Tengah", "Lombok Timur", "Lombok Utara", "Sumbawa", "Sumbawa Barat"],
    "Nusa Tenggara Timur": ["Kupang", "Alor", "Belu", "Ende", "Flores Timur", "Kepulauan Aru", "Kepulauan Tanimbar", "Kupang", "Lembata", "Malaka", "Manggarai", "Manggarai Barat", "Manggarai Timur", "Ngada", "Nagekeo", "Rote Ndao", "Sabu Raijua", "Sikka", "Sumba Barat", "Sumba Barat Daya", "Sumba Tengah", "Sumba Timur", "Timor Tengah Selatan", "Timor Tengah Utara"],
    "Papua": ["Jayapura", "Asmat", "Biak Numfor", "Boven Digoel", "Deiyai", "Dogiyai", "Intan Jaya", "Jayapura", "Jayawijaya", "Keerom", "Kepulauan Yapen", "Lanny Jaya", "Mamberamo Raya", "Mamberamo Tengah", "Mappi", "Merauke", "Nabire", "Paniai", "Pegunungan Bintang", "Puncak", "Puncak Jaya", "Sarmi", "Supiori", "Tolikara", "Waropen", "Yahukimo", "Yalimo"],
    "Papua Barat": ["Manokwari", "Sorong", "Bintuni", "Fakfak", "Kaimana", "Manokwari Selatan", "Raja Ampat", "Sorong Selatan", "Tambrauw", "Teluk Bintuni", "Teluk Wondama"],
    "Papua Selatan": ["Merauke", "Asmat", "Boven Digoel", "Mappi"],
    "Papua Tengah": ["Nabire", "Deiyai", "Dogiyai", "Intan Jaya", "Paniai", "Puncak", "Puncak Jaya", "Tolikara", "Yahukimo", "Yalimo"],
    "Papua Pegunungan": ["Wamena", "Jayawijaya", "Lanny Jaya", "Mamberamo Tengah", "Nduga", "Pegunungan Bintang", "Tolikara", "Yahukimo", "Yalimo"],
    "Riau": ["Pekanbaru", "Dumai", "Bengkalis", "Indragiri Hulu", "Indragiri Hilir", "Kampar", "Kepulauan Meranti", "Kuantan Singingi", "Pelalawan", "Rokan Hulu", "Rokan Hilir", "Siak"],
    "Sulawesi Barat": ["Mamuju", "Mamasa", "Majene", "Mamuju Tengah", "Pasangkayu", "Polman (Polewali Mandar)"],
    "Sulawesi Selatan": ["Makassar", "Palopo", "Parepare", "Bantaeng", "Barru", "Bone", "Bulukumba", "Enrekang", "Gowa", "Jeneponto", "Kepulauan Selayar", "Luwu", "Luwu Timur", "Luwu Utara", "Maros", "Pangkajene Dan Kepulauan", "Pinrang", "Sidenreng Rappang", "Sinjai", "Soppeng", "Takalar", "Tana Toraja", "Wajo"],
    "Sulawesi Tengah": ["Palu", "Banggai", "Banggai Kepulauan", "Buol", "Donggala", "Morowali", "Morowali Utara", "Palu", "Parigi Moutong", "Poso", "Sigi", "Tojo Una-Una", "Toli-Toli"],
    "Sulawesi Tenggara": ["Kendari", "Baubau", "Bombana", "Buton", "Buton Selatan", "Buton Tengah", "Buton Utara", "Konawe", "Konawe Kepulauan", "Konawe Selatan", "Konawe Utara", "Muna", "Muna Barat", "Wakatobi"],
    "Sulawesi Utara": ["Manado", "Bitung", "Tomohon", "Bolaang Mongondow", "Bolaang Mongondow Selatan", "Bolaang Mongondow Timur", "Bolaang Mongondow Utara", "Kepulauan Sangihe", "Kepulauan Siau Tagulandang", "Kepulauan Talaud", "Kotamobagu", "Minahasa", "Minahasa Selatan", "Minahasa Tenggara", "Minahasa Utara"],
    "Sumatera Barat": ["Padang", "Bukittinggi", "Payakumbuh", "Pariaman", "Sawahlunto", "Solok", "Agam", "Dharmasraya", "Kepulauan Mentawai", "Lima Puluh Kota", "Padang Pariaman", "Pesisir Selatan", "Sijunjung", "Solok Selatan", "Tanah Datar"],
    "Sumatera Selatan": ["Palembang", "Prabumulih", "Pagar Alam", "Lubuklinggau", "Banyuasin", "Empat Lawang", "Lahat", "Muara Enim", "Musi Banyuasin", "Musi Rawas", "Musi Rawas Utara", "Ogan Ilir", "Ogan Komering Ilir", "Ogan Komering Ulu", "Ogan Komering Ulu Selatan", "Ogan Komering Ulu Timur", "Penukal Abab Lematang Ilir"],
    "Sumatera Utara": ["Medan", "Binjai", "Tanjungbalai", "Pematangsiantar", "Tebing Tinggi", "Padang Sidempuan", "Gunungsitoli", "Asahan", "Batubara", "Dairi", "Deli Serdang", "Humbang Hasundutan", "Karo", "Labuhan Batu", "Labuhan Batu Selatan", "Labuhan Batu Utara", "Langkat", "Mandailing Natal", "Nias", "Nias Barat", "Nias Selatan", "Nias Utara", "Padang Lawas", "Padang Lawas Utara", "Pakpak Bharat", "Samosir", "Serdang Bedagai", "Simalungun", "Tapanuli Selatan", "Tapanuli Tengah", "Tapanuli Utara"],
  }
  return cities[province] || []
}

export const getDistrictsByCity = (city: string) => {
  const districts: Record<string, string[]> = {
    "Jakarta Pusat": ["Gambir", "Kemayoran", "Menteng", "Senen", "Tanah Abang"],
    "Jakarta Utara": ["Cilincing", "Kelapa Gading", "Koja", "Pademangan", "Penjaringan", "Tanjung Priok"],
    "Jakarta Selatan": ["Cilandak", "Jagakarsa", "Kebayoran Baru", "Kebayoran Lama", "Mampang Prapatan", "Pasar Minggu", "Pesanggrahan", "Setiabudi", "Tebet"],
    "Jakarta Timur": ["Cakung", "Cipayung", "Ciracas", "Duren Sawit", "Jatinegara", "Kramat Jati", "Makasar", "Matraman", "Pasar Rebo", "Pulo Gadung"],
    "Jakarta Barat": ["Cengkareng", "Grogol Petamburan", "Kebon Jeruk", "Kalideres", "Palmerah", "Taman Sari", "Tambora"],
    "Bandung": ["Bojongloa Kaler", "Bojongloa Kidul", "Cidadap", "Cicendo", "Cimahi Selatan", "Cimahi Tengah", "Cimahi Utara", "Cirebon Selatan", "Cirebon Utara", "Dago", "Kiaracondong", "Lengkong", "Mandalajati", "Panyileukan", "Regol", "Sukajadi", "Sukasari", "Ujung Berung"],
    "Surabaya": ["Asemrowo", "Benowo", "Bubutan", "Bulak", "Dukuh Pakis", "Gayungan", "Genteng", "Gubeng", "Gunung Anyar", "Jambangan", "Karang Pilang", "Kenjeran", "Krembangan", "Lakarsantri", "Mulyorejo", "Pabean Cantikan", "Pakal", "Rungkut", "Sambikerep", "Sawahan", "Semampir", "Simokerto", "Sukolilo", "Tandes", "Tambaksari", "Tegalsari", "Wonocolo", "Wonokromo"],
    "Medan": ["Medan Amplas", "Medan Area", "Medan Baru", "Medan Belawan", "Medan Denai", "Medan Deli", "Medan Helvetia", "Medan Johor", "Medan Kota", "Medan Labuhan", "Medan Maimun", "Medan Marelan", "Medan Polonia", "Medan Selayang", "Medan Sunggal", "Medan Tuntungan", "Medan Perjuangan", "Medan Timur", "Medan Barat"],
    "Bekasi": ["Bekasi Barat", "Bekasi Timur", "Bekasi Selatan", "Bekasi Utara", "Jatisampurna", "Jatiasih", "Medan Satria", "Mustikajaya", "Pondok Gede", "Pondok Melati", "Rawalumbu"],
    "Depok": ["Beji", "Bojongsari", "Cimanggis", "Cinere", "Cipayung", "Limo", "Pancoran Mas", "Sawangan", "Tapos"],
    "Bogor": ["Bogor Barat", "Bogor Selatan", "Bogor Tengah", "Bogor Timur", "Bogor Utara", "Tanah Sareal"],
    "Semarang": ["Semarang Barat", "Semarang Tengah", "Semarang Timur", "Semarang Utara", "Candisari", "Gayamsari", "Genuk", "Gajahmungkur", "Gunungpati", "Mijen", "Ngaliyan", "Pedurungan", "Tembalang", "Tugu"],
  }
  return districts[city] || []
}

export const getVillagesByDistrict = (district: string) => {
  const villages: Record<string, string[]> = {
    "Gambir": ["Cideng", "Duri Pulo", "Gambir", "Kebon Kelapa", "Petojo Selatan", "Petojo Utara"],
    "Kemayoran": ["Cempaka Putih Timur", "Cempaka Putih Barat", "Galur", "Gunung Sahari Selatan", "Kebon Kosong", "Kemayoran", "Serdang", "Sumur Batu", "Utan Panjang"],
    "Menteng": ["Cikini", "Kebon Sirih", "Menteng", "Pegangsaan", "Petamburan"],
    "Senen": ["Bungur", "Kampung Bali", "Kenari", "Kwitang", "Paseban", "Senen"],
    "Tanah Abang": ["Bendungan Hilir", "Karet Tengsin", "Kebon Kacang", "Kebon Melati", "Petamburan", "Tanah Abang"],
    "Beji": ["Beji", "Beji Timur", "Kukusan", "Pondok Jati", "Tanah Baru", "Tanjung Barat"],
    "Cimanggis": ["Cimanggis", "Curug", "Giri Mukti", "Harjamukti", "Kalisuren", "Krukut", "Mekarjaya", "Mekarsari", "Pasir Putih", "Pengasinan", "Sukamaju"],
  }
  return villages[district] || []
}
